
import React from 'react';
import { AnalysisResult } from '../types';
import { Markdown } from './Markdown';

interface AnalysisDisplayProps {
  result: AnalysisResult;
}

export const AnalysisDisplay: React.FC<AnalysisDisplayProps> = ({ result }) => {
  const getThreatColor = (level: string) => {
    switch (level) {
      case 'Critical': return 'text-red-600 border-red-600';
      case 'High': return 'text-red-400 border-red-400';
      case 'Medium': return 'text-yellow-500 border-yellow-500';
      default: return 'text-green-400 border-green-400';
    }
  };

  return (
    <div className="bg-black/80 border border-green-900/50 rounded-lg p-6 space-y-6 overflow-y-auto terminal-scrollbar max-h-[80vh]">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h2 className="text-2xl font-bold text-green-400 glitch-text tracking-wider uppercase">
            Forensic Report: {result.fileName}
          </h2>
          <p className="text-gray-400 text-xs">Analysis generated by HexSpec Intelligence Engine</p>
        </div>
        <div className={`px-4 py-1 border-2 rounded-full font-bold text-sm uppercase ${getThreatColor(result.threatLevel)}`}>
          Threat Level: {result.threatLevel}
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="bg-gray-900/50 p-4 border border-green-900/30 rounded">
          <h3 className="text-green-500 text-xs font-bold uppercase mb-2">Identification</h3>
          <div className="space-y-1">
            <p><span className="text-gray-500">True Type:</span> <span className="text-green-400">{result.detectedType}</span></p>
            <p><span className="text-gray-500">MIME Ext:</span> <span className="text-green-400">.{result.detectedExtension}</span></p>
            <p><span className="text-gray-500">Actual Ext:</span> <span className="text-gray-400">.{result.fileName.split('.').pop()}</span></p>
            <p><span className="text-gray-500">Size:</span> <span className="text-gray-400">{result.fileSize.toLocaleString()} bytes</span></p>
          </div>
        </div>

        <div className="bg-gray-900/50 p-4 border border-green-900/30 rounded">
          <h3 className="text-green-500 text-xs font-bold uppercase mb-2">Hex Signature</h3>
          <div className="flex flex-wrap gap-2 font-mono text-sm">
            {result.hexPreview.map((h, i) => (
              <span key={i} className="px-1.5 py-0.5 bg-green-950/50 text-green-300 border border-green-800/30 rounded">
                {h}
              </span>
            ))}
          </div>
          <p className="mt-2 text-[10px] text-gray-500 italic font-mono">
            Offset: {result.signatureMatch?.offset || 0} bytes
          </p>
        </div>
      </div>

      <div className="border-t border-green-900/30 pt-4">
        <h3 className="text-green-500 text-xs font-bold uppercase mb-3 flex items-center gap-2">
          <i className="fas fa-microchip"></i> Security Intelligence (Gemini AI)
        </h3>
        <div className="prose prose-invert prose-green max-w-none text-sm leading-relaxed text-gray-300 font-sans">
          <Markdown content={result.securityIntel} />
        </div>
      </div>
      
      <div className="flex gap-4 pt-4">
        <button 
          onClick={() => window.print()}
          className="flex-1 bg-green-900/20 hover:bg-green-800/40 border border-green-700/50 text-green-400 py-2 rounded transition-all text-xs font-bold uppercase"
        >
          <i className="fas fa-file-export mr-2"></i> Export PDF
        </button>
      </div>
    </div>
  );
};

const Markdown: React.FC<{ content: string }> = ({ content }) => {
    // Simple mock markdown renderer to avoid external dependencies for this specific display
    const lines = content.split('\n');
    return (
        <div className="space-y-4">
            {lines.map((line, idx) => {
                if (line.startsWith('# ')) return <h1 key={idx} className="text-xl font-bold text-green-400">{line.replace('# ', '')}</h1>;
                if (line.startsWith('## ')) return <h2 key={idx} className="text-lg font-bold text-green-400 border-b border-green-900/50 pb-1">{line.replace('## ', '')}</h2>;
                if (line.startsWith('### ')) return <h3 key={idx} className="text-md font-bold text-green-300">{line.replace('### ', '')}</h3>;
                if (line.startsWith('1. ') || line.startsWith('2. ') || line.startsWith('3. ') || line.startsWith('4. ') || line.startsWith('5. ')) {
                    return <div key={idx} className="pl-4 border-l-2 border-green-800 py-1 bg-green-950/10 mb-2">{line}</div>;
                }
                if (line.trim() === '') return <br key={idx} />;
                return <p key={idx}>{line}</p>;
            })}
        </div>
    );
};
